<?php

namespace Database\Seeders;

use App\Models\Patient;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PatientsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Patient::create([
            'user_id' => 11,
            'full_name' => 'نجلاء الحلبي',
            'gender' => 'أنثى',
            'birth_date' => '1950-3-05',
            'relationship_status' => 'أرمل',
            'address' => 'xx at xx street',
            'phone_number' => '09XXXXXXXX',
            'weight' => 90.5,
            'height' => 160,
            'previous_diseases_surgeries' => '',
            'chronic_diseases' => ' تعاني من دوالي القدمين ومرض السكري , وتراكم السوائل في الرئتين , لديها جلطة دماغية ',
            'current_medications' => 'منظم سكر ميتا فورال',
            'allergies' => '', //حساسيات
            'family_medical_history' => 'سكر وراثي و الشيب المبكر',
            'smoker' => false,
            'addiction' => '', // مدمن
            'exercise_frequency' => 'تمارين رياضية من خلال معالج فيزيائي',
            'diet_description' => 'ممتنعة عن أكل الحلويات والدهون',
            'current_symptoms' => '',
            'recent_vaccinations' => '',
        ]);
        Patient::create([
            'user_id' => 12,
            'full_name' => 'عبد الحكيم دلال',
            'gender' => 'ذكر',
            'birth_date' => '1953-05-14',
            'relationship_status' => 'متزوج',
            'address' => 'xx at xx street',
            'phone_number' => '09XXXXXXXX',
            'weight' => 110,
            'height' => 190,
            'previous_diseases_surgeries' => '',
            'chronic_diseases' => 'جلطة دماغية , المريض مقعد',
            'current_medications' => '',
            'allergies' => '',
            'family_medical_history' => '',
            'smoker' => true,
            'addiction' => '',
            'exercise_frequency' => '',
            'diet_description' => '',
            'current_symptoms' => '',
            'recent_vaccinations' => '',
        ]);

        Patient::create([
            'user_id' => 12,
            'full_name' => 'فاطمة خورشيد',
            'gender' => 'أنثى',
            'birth_date' => '1964-07-07',
            'relationship_status' => 'متزوج',
            'address' => 'xx at xx street',
            'phone_number' => '09XXXXXXXX',
            'weight' => 90,
            'height' => 166,
            'previous_diseases_surgeries' => '',
            'chronic_diseases' => '',
            'current_medications' => '',
            'allergies' => '',
            'family_medical_history' => '',
            'smoker' => true,
            'addiction' => '',
            'exercise_frequency' => '',
            'diet_description' => '',
            'current_symptoms' => '',
            'recent_vaccinations' => '',
        ]);
        Patient::create([
            'user_id' => 13,
            'full_name' => 'ثريا نابلسي',
            'gender' => 'أنثى',
            'birth_date' => '1950-1-06',
            'relationship_status' => 'متزوج',
            'address' => 'xx at xx street',
            'phone_number' => '09XXXXXXXX',
            'weight' => 90,
            'height' => 166,
            'previous_diseases_surgeries' => 'عملية سرطان ',
            'chronic_diseases' => 'سرطان , سكري , قرحة بالمعدة',
            'current_medications' => '',
            'allergies' => '',
            'family_medical_history' => 'سكري وراثي',
            'smoker' => true,
            'addiction' => '',
            'exercise_frequency' => '',
            'diet_description' => 'الامتناع عن البقوليات وبعض الخضار',
            'current_symptoms' => '',
            'recent_vaccinations' => '',
        ]);
        Patient::create([
            'user_id' => 14,
            'full_name' => 'أميمة الحلبي',
            'gender' => 'أنثى',
            'birth_date' => '1964-07-07',
            'relationship_status' => 'متزوج',
            'address' => 'xx at xx street',
            'phone_number' => '09XXXXXXXX',
            'weight' => 55,
            'height' => 169,
            'previous_diseases_surgeries' => '',
            'chronic_diseases' => '',
            'current_medications' => '',
            'allergies' => '',
            'family_medical_history' => '',
            'smoker' => true,
            'addiction' => '',
            'exercise_frequency' => '',
            'diet_description' => '',
            'current_symptoms' => '',
            'recent_vaccinations' => '',
        ]);
        Patient::create([
            'user_id' => 15,
            'full_name' => 'أحمد بسطاتي',
            'gender' => 'ذكر',
            'birth_date' => '1964-07-07',
            'relationship_status' => 'متزوج',
            'address' => 'xx at xx street',
            'phone_number' => '09XXXXXXXX',
            'weight' => 90,
            'height' => 166,
            'previous_diseases_surgeries' => '',
            'chronic_diseases' => '',
            'current_medications' => '',
            'allergies' => '',
            'family_medical_history' => '',
            'smoker' => true,
            'addiction' => '',
            'exercise_frequency' => '',
            'diet_description' => '',
            'current_symptoms' => '',
            'recent_vaccinations' => '',
        ]);
        Patient::create([
            'user_id' => 15,
            'full_name' => 'سامر بسطاتي',
            'gender' => 'ذكر',
            'birth_date' => '1964-07-07',
            'relationship_status' => 'متزوج',
            'address' => 'xx at xx street',
            'phone_number' => '09XXXXXXXX',
            'weight' => 90,
            'height' => 166,
            'previous_diseases_surgeries' => '',
            'chronic_diseases' => '',
            'current_medications' => '',
            'allergies' => '',
            'family_medical_history' => '',
            'smoker' => true,
            'addiction' => '',
            'exercise_frequency' => '',
            'diet_description' => '',
            'current_symptoms' => 'حرارة الجسم مرتفعة , جفاف في الفم والحلق ,سعال شديد',
            'recent_vaccinations' => 'لقاح كورونا',
        ]);
        Patient::create([
            'user_id' => 15,
            'full_name' => 'لبنى بسطاتي',
            'gender' => 'أنثى',
            'birth_date' => '1964-07-07',
            'relationship_status' => 'أعزب',
            'address' => 'xx at xx street',
            'phone_number' => '09XXXXXXXX',
            'weight' => 65,
            'height' => 166,
            'previous_diseases_surgeries' => '',
            'chronic_diseases' => 'ضعف في النظر وألم في الرأس وآلام في الرقبة والظهر',
            'current_medications' => 'تستخدم محلول للعين',
            'allergies' => 'حساسية من المقالي , والسكريات',
            'family_medical_history' => '',
            'smoker' => false,
            'addiction' => '',
            'exercise_frequency' => 'تمارين رياضية خفيفة بعد الجلوس الطويل على الموبايل واللابتوب',
            'diet_description' => '',
            'current_symptoms' => '',
            'recent_vaccinations' => '',
        ]);
    }
}
